name: build
on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
      - "*"
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run -E golint -E bodyclose
  build:
    runs-on: ubuntu-latest
    name: build
    needs: linting
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get dependencies
        run: make deps
      - name: Build & Test
        run: make build
      - name: Validate release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist
      - name: Scan image for vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.2.1
        with:
          args: --cache-dir /var/lib/trivy --exit-code 1 --no-progress whyeasy/zally-cleaner:${{ github.sha }}
